<script type="text/javascript">
    function getPageData($token)
    {
		jQuery("#loading-mask").show();
		jQuery("#loading_mask_loader").show();
      jQuery.ajax({
          url: "<?php echo Mage::getBaseUrl(); ?>lwmyoutube/index/loadData",
          type:'Post',
          data:{token:$token},
        context: document.body
      }).done(function(response) {
          jQuery('#video-list').html(response);
		  jQuery("#loading-mask").hide();
		  jQuery("#loading_mask_loader").hide();
		  jQuery('#vid_frame').scrollToMe();
      });
    }
function changeVideo(current){
	jQuery("#vid_frame").attr("src",jQuery(current).attr("data-iframe-src"));
	 jQuery('#vid_frame').scrollToMe();
}
</script>
<?php 
	$helper = Mage::helper('lwmyoutube');
	$channel_id = Mage::getStoreConfig('lwmyoutubesetting/general/channel');
	$videos = $helper->getVideos();
	$nextPageToken = $videos['nextPageToken'];
	$prevPageToken = $videos['prevPageToken'];
	$totalSize=$videos['totalResults'];
	Mage::getSingleton('core/session')->setPrevPageToken($prevPageToken);
	Mage::getSingleton('core/session')->setNextPageToken($nextPageToken);
  if($channel_id&&sizeof($videos)>0){
?>
   <div class="custVidwrap pad-25">
       <div class="vid-container">
          <iframe width="100%" height="315" id="vid_frame" src="https://www.youtube.com/embed/<?php echo $videos['items'][0]->snippet->resourceId->videoId;?>?autoplay=1&rel=0&showinfo=0&autohide=1" frameborder="0" allowfullscreen></iframe>
        </div>
	</div>
	<div id="video-list">
          <?php foreach ($videos['items'] as $key => $video) { 
			$url = $video->snippet->thumbnails->medium->url;
            ?>
            <div class="row video">
			<div class="yt-lockup-thumbnail col-md-4">
                <a href="javascript:void(0);" onclick="changeVideo(this)" data-iframe-src="//www.youtube.com/embed/<?php echo $video->snippet->resourceId->videoId; ?>?autoplay=1&rel=0&showinfo=0&autohide=1">
                    <img src="<?php echo $url; ?>" alt="<?php echo $media->group->title; ?>"/>
                </a>
			</div>
            <div class="yt-lockup-content col-md-8">			
                <h3><a href="javascript:void(0);" onClick="changeVideo(this)" data-iframe-src="//www.youtube.com/embed/<?php echo $video->snippet->resourceId->videoId; ?>?autoplay=1&rel=0&showinfo=0&autohide=1" ><?php echo $video->{'snippet'}->{'title'} ?></a>          </h3>
				<div class="youtube-date">
				<?php 
				$today     = new DateTime();
				$publishedAt = new DateTime($video->snippet->publishedAt);
				$interval  = $today->diff($publishedAt);
				$year=$interval->format('%y');
				if($year){
					echo $year=$interval->format('%y years ago ');
				}else{
					echo $interval->format('%m months ago');
				}
				?>
				</div>
				<?php 
				$description = strip_tags($video->snippet->description);

					if (strlen($description) > 180) {

						// truncate string
						$stringCut = substr($description, 0, 180);

						// make sure it ends in a word so assassinate doesn't become ass...
						$description = substr($stringCut, 0, strrpos($stringCut, ' ')).'...'; 
					}
					
?>
                 <p><?php echo $description; ?></p>
			</div>	 
            </div>
          <?php } ?>
    </div>
    <div style="clear:both;"></div>
	<?php if($totalSize>6){?>
          <ul class="pagination">
            <li>
              <a onclick="getPageData('prev')">Previous</a>
            </li>
            <li>
              <a onclick="getPageData('next')">Next</a>
            </li>
          </ul>
	<?php }?>	  
<style>
.video{
	margin-bottom:10px;
}
.std .pagination {
    border-radius: 4px;
    display: inline-block;
    margin: 20px 0;
    padding-left: 0;
}
.pagination > li {
    display: inline;
}
.pagination > li > a, .pagination > li > span {
    background-color: #fff;
    border: 1px solid #ddd;
    float: left;
    line-height: 1.42857;
    margin-left: -1px;
    padding: 6px 12px;
    position: relative;
    text-decoration: none;
	border-radius: 4px;
}

.yt-lockup-content.col-md-8 a {
    color: #167ac6;
}

</style>		
  <?php } ?> 
  